<html>
<head>
<title>Terms and Condition</title>
<link rel="stylesheet" type="text/css" href="stylecs.css" />
</head>
<body style="width:100%">
<div class="container" style="margin-top: 5%">

<h3><strong>Bus ticket reservation - Terms and Conditions</strong></h3>
<br><br>
<p>These terms and conditions (collectively, hereinafter referred to as the "Terms") govern your ("User") access to and use of the website, www.redbus.in and the redBus mobile applications ("Website"). The Website is owned, managed and operated by IBIBO Group Private Limited ("redBus").

<br><br>Please read these Terms carefully before using the Website, which is an online marketplace. For the purpose of clarity, it is hereby stated that the Website is not engaged in providing any services by itself but is a platform, which merely connects the bus operators with the bus travellers.

<br><br>These Terms are an electronic record in terms of the applicable legislation. This electronic record is generated by a computer system and does not require any physical or digital signatures. By using the Website, you signify your agreement to be bound by these Terms.

<br><br>redBus allows You to surf the Website or buy bus tickets for yourself, your family and your friends, without registering on the Website. You shall be deemed to have read, understood and expressly accepted these Terms, which shall govern the desired transaction of bus ticket booking through the Website for all purposes, and shall be binding on You. All Your rights and liabilities and/or the Website with respect to Your use of the Website and availing bus ticket booking facility ("Facility") provided by the Website shall be governed by these Terms.

<br><br>PLEASE NOTE THAT YOUR USE OF THE WEBSITE IN ANY WAY SIGNIFIES YOUR ACCEPTANCE TO THE TERMS. By agreeing to these Terms, You also agree to redBus' other Website policies; including but not limited to, (i) Privacy Policy, as amended from time to time; and (ii) Cookie Policy.

<br><br>In addition to these Terms, any other ‘terms of service’ of the application-programming interface (“API”) with which redBus may tie-up would form an integral part of these Terms (hereinafter referred to as the “API Terms”). However, in the event of a conflict between such API Terms and these Terms, these Terms provided herein shall prevail.

Both You and redBus are individually referred to as 'Party' and collective referred to as 'Parties', in these Terms.</p></div>

<?php 
include "header.php";
			include "nav.php"; ?>
			<div class="container">
				<div class="col-sm-10">

		    </div>
				<br>

			<div class="row">
						<div class="container">

							<div class="jumbotron ">

								<div class="container">

									<div class="row">

										<div class="col-sm-4">
											<h3>Our Products</h3>
											<h5>
											<a href="./index.php">Bus Booking</a><br>
											</h5>
											<h5>
												<a href="/cabs">Cabs Booking</a><br>
											</h5>
											<h5>
												<a href="./terms.php">Terms & Condition</a><br>
											</h5>
										</div>

										<div class="col-sm-4">
											<h3>Company</h3>
											<h5>
												<a href="./about.php">About Us</a><br>
											</h5>
											<h5>
												<a href="./privacy.php">Privacy Policy</a><br>
											</h5>
											<h5>
												<a href="./feedback.php">Feedback</a><br>
											</h5>

										</div>

										<div class="col-sm-4">
											<h3>More Links</h3>
											<h5>
												<a href="/getTicket?to=print">Print E-Ticket</a><br>
											</h5>
											<h5>
												<a href="./custsupport.php">Customer Support</a><br>
											</h5>
											<h5>
												<a href="getTicket?to=cancel">Cancel Tickets</a><br>
											</h5>						

										</div>
									</div>
								</div>
							</div>



							
							<div class="well">

								<div class="container">

									<div class="row">

										<div class="col-sm-4">
											<h4>Download our Moblie Apps</h4>

											<div class="d-apps">
												<ul>
													<li><a href="#"><img src="images/app1.png" alt="" /></a></li>
													<li><a href="#"><img src="images/app2.png" alt="" /></a></li>
													<li><a href="#"><img src="images/app3.png " alt="" /></a></li>
												</ul>
											</div>
		                                </div>
										<div class="col-sm-4">
											<h4>We Accept</h4>


											<div class="d-apps">
												<ul>
													<li><a href="#"><img src="images/c1.png" alt="" /></a></li>
													<li><a href="#"><img src="images/c2.png" alt="" /></a></li>
													<li><a href="#"><img src="images/c3.png" alt="" /></a></li>
												</ul>
											</div>
										</div>
										<div class="col-sm-4">

											<h4>Follow Us On</h4>

											<div class="social">
												<ul>
													<li><a href="#" class="facebook"> </a></li>
													<li><a href="#" class="facebook twitter"> </a></li>
													<li><a href="#" class="facebook chrome"> </a></li>
													<li><a href="#" class="facebook dribbble"> </a></li>
												</ul>
											</div>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

            </div>
            <br><br>
            <div class="row">
            
	            <div class="container">

				    <div class="footer"><hr>
								
						<footer>
							<div class="row">

								<div class="col-lg-12">
									<b><p>Copyrights © 2019 Xtreme Travels.</p></b>
								</div>
							</div>
						</footer>
					</div>
				</div>
			</div>

					
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!--<script src="bootstrap.min.js"></script>-->
<!-- <script src="jquery.dataTables.js"></script>-->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js "></script> 

<script src="script.js"></script> 
			
	    </div>
	</body>
</html>
